// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrqpmdlgfzvrtypgerhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndycXBtZGxnZnp2cnR5cGdlcmhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MDk1OTQsImV4cCI6MjA2NTI4NTU5NH0.Bjg6DgGKcY4-fdHAqURRG3M9OJ70T6FZhJpmYUIQ58s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);